image: docker:latest


default:
  tags:
    - linux
    - docker
    - gitlab-org
    - gitlab-org-docker


stages:
  - docker-images
  - build



variables:
  IMAGES_PREFIX: $CI_REGISTRY_IMAGE/env_


.generate-minimal-dockerfile:
  variables:
    DOCKERFILE: "ci/Dockerfile"
  services:
    - docker:dind
  before_script:
    - mkdir -p ci
    - |
        cat <<EOT >> $DOCKERFILE
          ARG BASE_IMAGE=gcc:13-bookworm
          FROM \$BASE_IMAGE

          RUN set -xe \
            && apt-get update \
            && apt-get install -y cmake

          RUN set -xe \
            && cd /tmp \
            && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz \
            && tar xzf eigen-3.4.0.tar.gz \
            && cd eigen-3.4.0 \
            && mkdir build \
            && cd build \
            && cmake .. \
            && make install \
            && cd ../.. \
            && rm -rf eigen-3.4.0.tar.gz eigen-3.4.0
        EOT


build-docker-images-gcc:
  stage: docker-images
  extends: .generate-minimal-dockerfile
  variables:
    COMPILER: "gcc"
  script:
    - VERSION=$(echo ${COMPILER_VERSION%-*})
    - IMAGE_NAME="${IMAGES_PREFIX}${COMPILER}:${VERSION}"
    - BASE_IMAGE="gcc:${COMPILER_VERSION}"
    - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker pull ${IMAGE_NAME} || echo "Image not found"
    - docker build -t ${IMAGE_NAME} --build-arg BASE_IMAGE=${BASE_IMAGE} -f ${DOCKERFILE} .
    - docker push ${IMAGE_NAME}
  parallel:
    matrix:
      - COMPILER_VERSION: ["10-bullseye", "11-bullseye", "12-bullseye", "13-bookworm"]


build-docker-images-clang:
  stage: docker-images
  extends: .generate-minimal-dockerfile
  variables:
    COMPILER: "clang"
  script:
    - VERSION=$(echo ${COMPILER_VERSION%-*})
    - IMAGE_NAME="${IMAGES_PREFIX}${COMPILER}:${VERSION}"
    - BASE_IMAGE="silkeh/clang:${COMPILER_VERSION}"
    - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker pull ${IMAGE_NAME} || echo "Image not found"
    - docker build -t ${IMAGE_NAME} --build-arg BASE_IMAGE=${BASE_IMAGE} -f ${DOCKERFILE} .
    - docker push ${IMAGE_NAME}
  parallel:
    matrix:
      - COMPILER_VERSION: ["13-bullseye", "14-bullseye", "15-bullseye", "16-bullseye"]


build-gafro:
  stage: build
  image:
    name: ${IMAGES_PREFIX}${COMPILER}:${COMPILER_VERSION}
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install
  parallel:
    matrix:
      - COMPILER: gcc
        COMPILER_VERSION: [10, 11, 12, 13]
      - COMPILER: clang
        COMPILER_VERSION: [13, 14, 15, 16]