[package]
name = "gafro_test_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
