[package]
name = "gafro_modern_showcase"
version = "0.1.0"
edition = "2021"

[dependencies]
gafro_modern = { path = "../../rust_modern" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"